import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "@/sass/style.scss";
import "@/sass/main.scss";
const inter = Public_Sans({ subsets: ["vietnamese"] });
import MainStore from "@/context/MainContext";
import FinanceStore from "@/context/FinanceContext";
import { DetailContext } from "@/context/DetailContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <FinanceStore>
          <MainStore>{children}</MainStore>
        </FinanceStore>
      </body>
    </html>
  );
}
