import React from "react";

export const metadata = {
  title: "Detail",
  description: "Generated by create next app",
};

export default function PublisherLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
