import React from "react";
import FinanceStore from "@/context/FinanceContext";
import DetailStore from "@/context/DetailContext";
export const metadata = {
  title: "Detail",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <DetailStore>
        <FinanceStore>{children}</FinanceStore>
      </DetailStore>
    </div>
  );
}
